// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBybAeDI-PPjQmv9OkkYd2-3Mjug6VjFUo',
    appId: '1:68587916563:web:9284f0324a080d76c59ee6',
    messagingSenderId: '68587916563',
    projectId: 'dante-sleep',
    authDomain: 'dante-sleep.firebaseapp.com',
    storageBucket: 'dante-sleep.firebasestorage.app',
    measurementId: 'G-11CYRJGV5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPM7mClAeizMfO5SdE6deGd1goBUflgKE',
    appId: '1:68587916563:android:c26cee328eeb6c25c59ee6',
    messagingSenderId: '68587916563',
    projectId: 'dante-sleep',
    storageBucket: 'dante-sleep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPI9NmsGw-txdL3lE8YtmNegK1NLZOuRk',
    appId: '1:68587916563:ios:cf99d2f0d54675abc59ee6',
    messagingSenderId: '68587916563',
    projectId: 'dante-sleep',
    storageBucket: 'dante-sleep.firebasestorage.app',
    iosBundleId: 'com.example.danteSleep',
  );
}
